/var/www/prebuiltapi.com/backend/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0660 pm2 pm2
    sharedscripts
    postrotate
        pm2 reloadLogs
    endscript
}
