const { Worker } = require('bullmq');
const redisConnection = require('../services/redisConnection');
const prisma = require('../prismaClient');
const CheckoutManager = require('../services/payments/CheckoutManager');
const { decrypt } = require('../utils/encryption');
const MetaApiService = require('../services/MetaApiService');

const workerOptions = {
    connection: redisConnection,
    concurrency: 5,
    limiter: {
        max: 50,
        duration: 1000
    }
};

const paymentEventWorker = new Worker('payment.events', async job => {
    const { workspaceId, linkId, paymentLinkEntity, eventId } = job.data;
    
    console.log(`[PaymentEventWorker] Processing payment link ${linkId} for workspace ${workspaceId}`);

    try {
        // 1. Mark CheckoutSession as paid
        const session = await CheckoutManager.findByExternalId(linkId);
        
        if (!session) {
            console.warn(`[PaymentEventWorker] No checkout session found for external ID ${linkId}. Ignored.`);
            await prisma.webhookEvent.update({
                where: { externalEventId: eventId },
                data: { status: 'processed', errorLog: 'No checkout session found' }
            });
            return;
        }

        if (session.status === 'paid') {
            console.log(`[PaymentEventWorker] Session ${linkId} is already marked paid.`);
            await prisma.webhookEvent.update({
                where: { externalEventId: eventId },
                data: { status: 'processed' }
            });
            return;
        }

        let newOrderId = null;
        let createdOrder = null;
        let finalStore = null;

        // Start atomic database transaction
        await prisma.$transaction(async (tx) => {
            // 2. Mark as paid atomically
            const updatedCount = await CheckoutManager.markAsPaid(linkId, tx);
            
            if (updatedCount === 0) {
                console.log(`[PaymentEventWorker] Session ${linkId} was already marked paid by another process.`);
                return;
            }

            // 3. Auto-Create default EcomStore if missing so workspace can still persist orders!
            let store = await tx.ecomStore.findFirst({
                where: { userId: workspaceId }
            });

            if (!store) {
                store = await tx.ecomStore.create({
                    data: {
                        userId: workspaceId,
                        storeName: "WhatsApp AI Store",
                        platform: "custom",
                        status: "connected"
                    }
                });
                console.log(`[PaymentEventWorker] Created default EcomStore for workspace ${workspaceId}`);
            }
            finalStore = store;

            const orderAmount = session.amount;
            const contactPhone = session.contactPhone;

            // Generate clean order ID
            const orderTimestamp = Date.now().toString().slice(-6);
            const externalOrderId = `AI_ORD_${orderTimestamp}`;

            // Store order record
            const newOrder = await tx.ecomOrder.create({
                data: {
                    userId: workspaceId,
                    storeId: store.id,
                    externalOrderId,
                    customerPhone: contactPhone,
                    orderStatus: 'confirmed',
                    paymentStatus: 'paid',
                    paymentMethod: 'razorpay',
                    totalAmount: orderAmount,
                    currency: session.currency || "INR",
                    lineItems: session.lineItems,
                    notes: `Autogenerated via AI Payment Link ${linkId}`
                }
            });

            newOrderId = newOrder.id;
            createdOrder = newOrder;
            console.log(`[PaymentEventWorker] Created EcomOrder ${newOrder.id} for workspace ${workspaceId}`);

            // Mark WebhookEvent as processed inside transaction
            await tx.webhookEvent.update({
                where: { externalEventId: eventId },
                data: { status: 'processed', processedAt: new Date() }
            });
        });

        // 4. Trigger Monospaced Tax Invoice Dispatch on WhatsApp (outside transaction block)
        if (createdOrder && finalStore) {
            try {
                // Fetch workspace invoice/payment configuration settings
                const settingsRecord = await prisma.systemSetting.findUnique({
                    where: { key: `payment_settings_${workspaceId}` }
                });

                let settings = {
                    currency: 'INR',
                    taxRate: '18',
                    shippingAmt: '0',
                    codEnabled: false,
                    invoicePrefix: 'INV-',
                    invoiceTerms: 'Thank you for your business!',
                    autoGenerateInvoice: true
                };

                if (settingsRecord) {
                    try {
                        settings = { ...settings, ...JSON.parse(settingsRecord.value) };
                    } catch (e) {
                        console.error("[PaymentEventWorker] Failed to parse payment settings:", e);
                    }
                }

                // If invoice auto-generation is enabled, calculate tax & shipping splits
                if (settings.autoGenerateInvoice) {
                    const totalAmt = Number(createdOrder.totalAmount);
                    const shippingFee = Number(settings.shippingAmt) || 0;
                    const taxRatePct = Number(settings.taxRate) || 0;

                    // Inclusive Tax Split logic: Grand Total = SubtotalBeforeShipping (which is inclusive of tax) + Shipping
                    const subtotalBeforeShipping = Math.max(0, totalAmt - shippingFee);
                    const preTaxSubtotal = subtotalBeforeShipping / (1 + (taxRatePct / 100));
                    const taxAmount = subtotalBeforeShipping - preTaxSubtotal;

                    // Resolve line items description
                    let itemsStr = "";
                    if (Array.isArray(createdOrder.lineItems) && createdOrder.lineItems.length > 0) {
                        createdOrder.lineItems.forEach((item, index) => {
                            const name = item.name || "Product";
                            const price = Number(item.price) || totalAmt;
                            itemsStr += `${index + 1}. ${name.padEnd(20).substring(0, 20)} x 1  ${settings.currency} ${price.toFixed(2)}\n`;
                        });
                    } else {
                        itemsStr += `1. General Product      x 1  ${settings.currency} ${subtotalBeforeShipping.toFixed(2)}\n`;
                    }

                    // Format monospaced Tax Receipt block for premium UX on WhatsApp
                    const monospacedReceipt = 
`\`\`\`
========================================
         TAX INVOICE / RECEIPT          
========================================
Invoice No : ${settings.invoicePrefix || 'INV-'}${createdOrder.externalOrderId.substring(7)}
Date       : ${new Date().toLocaleDateString()}
Store      : ${finalStore.storeName}
========================================
CUSTOMER DETAILS:
Phone      : ${createdOrder.customerPhone}
========================================
ORDER DETAILS:
${itemsStr}========================================
CALCULATIONS:
Subtotal   : ${settings.currency} ${preTaxSubtotal.toFixed(2)}
Tax (${taxRatePct}%)  : ${settings.currency} ${taxAmount.toFixed(2)}
Shipping   : ${settings.currency} ${shippingFee.toFixed(2)}
========================================
GRAND TOTAL: ${settings.currency} ${totalAmt.toFixed(2)}
========================================
Terms: ${settings.invoiceTerms || 'Thank you for your business!'}
========================================
Thank you for shopping with us!
========================================
\`\`\``;

                    // Resolve workspace-specific Meta token & number details
                    const user = await prisma.user.findUnique({
                        where: { id: workspaceId }
                    });

                    if (user && user.metaToken && user.phoneNumberId) {
                        const token = decrypt(user.metaToken);
                        const phoneNumberId = user.phoneNumberId;

                        console.log(`[PaymentEventWorker] Dispatching WhatsApp Tax Receipt to ${createdOrder.customerPhone}`);
                        
                        await MetaApiService.sendText({
                            phoneNumberId,
                            token,
                            to: createdOrder.customerPhone,
                            text: `Thank you for your payment! Here is your official purchase receipt:\n\n${monospacedReceipt}`,
                            context: { userId: workspaceId, type: 'invoice-receipt', recipient: createdOrder.customerPhone }
                        });
                    } else {
                        console.warn(`[PaymentEventWorker] Workspace ${workspaceId} lacks meta credentials. Monospaced receipt skipped.`);
                    }
                }
            } catch (invoiceErr) {
                console.error("[PaymentEventWorker] Failed to generate/dispatch tax invoice:", invoiceErr.message);
            }
        }

    } catch (error) {
        console.error(`[PaymentEventWorker] Error processing job ${job.id}:`, error);
        
        await prisma.webhookEvent.update({
            where: { externalEventId: eventId },
            data: { status: 'failed', errorLog: error.message }
        });
        
        throw error; // Let BullMQ handle exponential backoff retry
    }

}, workerOptions);

paymentEventWorker.on('failed', (job, err) => {
    console.error(`[PaymentEventWorker] Job ${job.id} failed with error: ${err.message}`);
});

paymentEventWorker.on('completed', (job) => {
    console.log(`[PaymentEventWorker] Job ${job.id} has completed successfully`);
});

module.exports = { paymentEventWorker };
