const prisma = require('../../prismaClient');

class CheckoutManager {
    /**
     * Create a new checkout session record in the DB before calling Razorpay
     * @param {string} userId - The workspace user ID
     * @param {string} contactPhone - The WhatsApp contact phone
     * @param {number} amount - Amount in whole rupees
     * @param {Object} lineItems - Array of products or items being purchased
     * @returns {Object} The created CheckoutSession record
     */
    static async createSession(userId, contactPhone, amount, lineItems) {
        // Automatically expire in 1 hour
        const expiresAt = new Date(Date.now() + 60 * 60 * 1000); 

        return await prisma.checkoutSession.create({
            data: {
                userId,
                contactPhone,
                externalId: "pending_" + Date.now(), // Will be updated once Razorpay Link is generated
                url: "",
                amount,
                status: "pending",
                lineItems: lineItems,
                metadata: {},
                expiresAt
            }
        });
    }

    /**
     * Update an existing session with Razorpay Link details
     * @param {string} sessionId - The internal DB session ID
     * @param {string} razorpayLinkId - The Razorpay plink_xxx ID
     * @param {string} shortUrl - The short URL generated by Razorpay
     */
    static async attachRazorpayLink(sessionId, razorpayLinkId, shortUrl) {
        return await prisma.checkoutSession.update({
            where: { id: sessionId },
            data: {
                externalId: razorpayLinkId,
                url: shortUrl,
                status: "issued"
            }
        });
    }

    /**
     * Mark a session as paid using atomic update to prevent duplicate order generation.
     * @param {string} externalId - The Razorpay Link ID
     * @param {Object} [tx] - Optional Prisma transaction client
     * @returns {number} The number of records updated (should be 1 if successful, 0 if already paid)
     */
    static async markAsPaid(externalId, tx = prisma) {
        const result = await tx.checkoutSession.updateMany({
            where: { externalId, status: "issued" },
            data: {
                status: "paid",
                paidAt: new Date()
            }
        });
        return result.count;
    }

    /**
     * Find a session by its external Razorpay Link ID
     */
    static async findByExternalId(externalId) {
        return await prisma.checkoutSession.findUnique({
            where: { externalId }
        });
    }

    /**
     * Verify if the contact already has an active, unpaid session for similar amount/items to avoid duplicates
     * @returns {Object|null} The existing session if found
     */
    static async getActiveSession(userId, contactPhone) {
        const activeSession = await prisma.checkoutSession.findFirst({
            where: {
                userId,
                contactPhone,
                status: "issued",
                expiresAt: {
                    gt: new Date() // Not expired
                }
            },
            orderBy: {
                createdAt: 'desc'
            }
        });
        return activeSession;
    }
}

module.exports = CheckoutManager;
